[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "FHAZHBEeRdSmLUhdZz15D35GataRrXxMY8sbXBEMQq1f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
